//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFinderClient.ClassFinderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/ClassFinderService")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Crn {
            get {
                return this.CrnField;
            }
            set {
                if ((this.CrnField.Equals(value) != true)) {
                    this.CrnField = value;
                    this.RaisePropertyChanged("Crn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Instructor {
            get {
                return this.InstructorField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorField, value) != true)) {
                    this.InstructorField = value;
                    this.RaisePropertyChanged("Instructor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ClassFinderService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GpaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfCoursesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gpa {
            get {
                return this.GpaField;
            }
            set {
                if ((this.GpaField.Equals(value) != true)) {
                    this.GpaField = value;
                    this.RaisePropertyChanged("Gpa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfCourses {
            get {
                return this.NumberOfCoursesField;
            }
            set {
                if ((this.NumberOfCoursesField.Equals(value) != true)) {
                    this.NumberOfCoursesField = value;
                    this.RaisePropertyChanged("NumberOfCourses");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClassFinderServiceReference.IClassFinderService")]
    public interface IClassFinderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAllCourses", ReplyAction="http://tempuri.org/IClassFinderService/GetAllCoursesResponse")]
        ClassFinderClient.ClassFinderServiceReference.Course[] GetAllCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAllCourses", ReplyAction="http://tempuri.org/IClassFinderService/GetAllCoursesResponse")]
        System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Course[]> GetAllCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAllStudents", ReplyAction="http://tempuri.org/IClassFinderService/GetAllStudentsResponse")]
        ClassFinderClient.ClassFinderServiceReference.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAllStudents", ReplyAction="http://tempuri.org/IClassFinderService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Student[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetStudentsInCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetStudentsInCourseResponse")]
        ClassFinderClient.ClassFinderServiceReference.Student[] GetStudentsInCourse(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetStudentsInCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetStudentsInCourseResponse")]
        System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Student[]> GetStudentsInCourseAsync(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/AddStudentToCourse", ReplyAction="http://tempuri.org/IClassFinderService/AddStudentToCourseResponse")]
        bool AddStudentToCourse(int id, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/AddStudentToCourse", ReplyAction="http://tempuri.org/IClassFinderService/AddStudentToCourseResponse")]
        System.Threading.Tasks.Task<bool> AddStudentToCourseAsync(int id, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/RemoveStudentFromCourse", ReplyAction="http://tempuri.org/IClassFinderService/RemoveStudentFromCourseResponse")]
        void RemoveStudentFromCourse(int id, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/RemoveStudentFromCourse", ReplyAction="http://tempuri.org/IClassFinderService/RemoveStudentFromCourseResponse")]
        System.Threading.Tasks.Task RemoveStudentFromCourseAsync(int id, int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetMaxGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetMaxGpaForCourseResponse")]
        double GetMaxGpaForCourse(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetMaxGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetMaxGpaForCourseResponse")]
        System.Threading.Tasks.Task<double> GetMaxGpaForCourseAsync(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAverageGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetAverageGpaForCourseResponse")]
        double GetAverageGpaForCourse(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetAverageGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetAverageGpaForCourseResponse")]
        System.Threading.Tasks.Task<double> GetAverageGpaForCourseAsync(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetMinGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetMinGpaForCourseResponse")]
        double GetMinGpaForCourse(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/GetMinGpaForCourse", ReplyAction="http://tempuri.org/IClassFinderService/GetMinGpaForCourseResponse")]
        System.Threading.Tasks.Task<double> GetMinGpaForCourseAsync(int crn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/CreateNewStudent", ReplyAction="http://tempuri.org/IClassFinderService/CreateNewStudentResponse")]
        bool CreateNewStudent(int id, string name, double gpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/CreateNewStudent", ReplyAction="http://tempuri.org/IClassFinderService/CreateNewStudentResponse")]
        System.Threading.Tasks.Task<bool> CreateNewStudentAsync(int id, string name, double gpa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/CreateNewCourse", ReplyAction="http://tempuri.org/IClassFinderService/CreateNewCourseResponse")]
        bool CreateNewCourse(int crn, string title, string instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassFinderService/CreateNewCourse", ReplyAction="http://tempuri.org/IClassFinderService/CreateNewCourseResponse")]
        System.Threading.Tasks.Task<bool> CreateNewCourseAsync(int crn, string title, string instructor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassFinderServiceChannel : ClassFinderClient.ClassFinderServiceReference.IClassFinderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassFinderServiceClient : System.ServiceModel.ClientBase<ClassFinderClient.ClassFinderServiceReference.IClassFinderService>, ClassFinderClient.ClassFinderServiceReference.IClassFinderService {
        
        public ClassFinderServiceClient() {
        }
        
        public ClassFinderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassFinderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassFinderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassFinderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClassFinderClient.ClassFinderServiceReference.Course[] GetAllCourses() {
            return base.Channel.GetAllCourses();
        }
        
        public System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Course[]> GetAllCoursesAsync() {
            return base.Channel.GetAllCoursesAsync();
        }
        
        public ClassFinderClient.ClassFinderServiceReference.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public ClassFinderClient.ClassFinderServiceReference.Student[] GetStudentsInCourse(int crn) {
            return base.Channel.GetStudentsInCourse(crn);
        }
        
        public System.Threading.Tasks.Task<ClassFinderClient.ClassFinderServiceReference.Student[]> GetStudentsInCourseAsync(int crn) {
            return base.Channel.GetStudentsInCourseAsync(crn);
        }
        
        public bool AddStudentToCourse(int id, int crn) {
            return base.Channel.AddStudentToCourse(id, crn);
        }
        
        public System.Threading.Tasks.Task<bool> AddStudentToCourseAsync(int id, int crn) {
            return base.Channel.AddStudentToCourseAsync(id, crn);
        }
        
        public void RemoveStudentFromCourse(int id, int crn) {
            base.Channel.RemoveStudentFromCourse(id, crn);
        }
        
        public System.Threading.Tasks.Task RemoveStudentFromCourseAsync(int id, int crn) {
            return base.Channel.RemoveStudentFromCourseAsync(id, crn);
        }
        
        public double GetMaxGpaForCourse(int crn) {
            return base.Channel.GetMaxGpaForCourse(crn);
        }
        
        public System.Threading.Tasks.Task<double> GetMaxGpaForCourseAsync(int crn) {
            return base.Channel.GetMaxGpaForCourseAsync(crn);
        }
        
        public double GetAverageGpaForCourse(int crn) {
            return base.Channel.GetAverageGpaForCourse(crn);
        }
        
        public System.Threading.Tasks.Task<double> GetAverageGpaForCourseAsync(int crn) {
            return base.Channel.GetAverageGpaForCourseAsync(crn);
        }
        
        public double GetMinGpaForCourse(int crn) {
            return base.Channel.GetMinGpaForCourse(crn);
        }
        
        public System.Threading.Tasks.Task<double> GetMinGpaForCourseAsync(int crn) {
            return base.Channel.GetMinGpaForCourseAsync(crn);
        }
        
        public bool CreateNewStudent(int id, string name, double gpa) {
            return base.Channel.CreateNewStudent(id, name, gpa);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewStudentAsync(int id, string name, double gpa) {
            return base.Channel.CreateNewStudentAsync(id, name, gpa);
        }
        
        public bool CreateNewCourse(int crn, string title, string instructor) {
            return base.Channel.CreateNewCourse(crn, title, instructor);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewCourseAsync(int crn, string title, string instructor) {
            return base.Channel.CreateNewCourseAsync(crn, title, instructor);
        }
    }
}
